### ISSUE TITLE
Exception when running configure with gz-source

### ISSUE THREAD

**Issue by jcjdammers** [elbowz/tv_grab_xml#1]
Hi Elbowz,

When I run the configure for the following xml-source (gz-file) then I get an exception (see below).
Can you help me?
Thanks and regards,
Jeroen Dammers

http://universalepg.com/tvgids/gz

tv_grab_xml --configure --xml-source http://universalepg.com/tvgids/gz --config-file ./config.json

Traceback (most recent call last):
  File "./tv_grab_xml", line 298, in <module>
    main()
  File "./tv_grab_xml", line 86, in main
    write_config_json(args.config_file, args.xml_source, xml_source_file)
  File "./tv_grab_xml", line 170, in write_config_json
    for event, element in XmlParser.iterparse(xml_source_file, events=('start', 'end')):
  File "/var/packages/python3/target/lib/python3.7/xml/etree/ElementTree.py", line 1222, in iterator
    yield from pullparser.read_events()
  File "/var/packages/python3/target/lib/python3.7/xml/etree/ElementTree.py", line 1297, in read_events
    raise event
  File "/var/packages/python3/target/lib/python3.7/xml/etree/ElementTree.py", line 1269, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

**Comment by elbowz** [comment]
Hi @jcjdammers,

 because the script check if the file is gzipped by extension (ie. gz), and your file has no extension.

as temporary workaround you can change the line:

`if source[-3:] == '.gz':`
to
`if source[-2:] == 'gz':`

I'm working on a new release and should be out in a couple of days

**Comment by jcjdammers** [comment]
Great @elbowz , many thanks !!

**Comment by elbowz** [comment]
ehmmm, sorry @jcjdammers...it's not past a couple of days, but anyway the issue should be fixed also in the master :)

now, if the xml file is not auto-discovered as gzip, you can add the cli option `-g` or `--force-gzip`.

**Comment by jcjdammers** [comment]
thanks
