### ISSUE TITLE
Help with duplicated channels

### ISSUE THREAD

**Issue by jorges4lu2** [elbowz/tv_grab_xml#2]
Hi Elbowz,

I have some duplicate channels in my list (same channel but different quality), and I'd like to get epg for all of them, but your script right now is only keeping the ultimate channel of those duplicated in the .config.

Can you help me?
Thanks and regards

**Comment by elbowz** [comment]
It's a really old project and I remember quite nothing about it 😅

Anyway try post on pastebin or here the duplicate channels of your EPG (ie XML).

It's strange that channel **Id** is a duplicate, i guess it was a unique key inside the XML EPG.

**Comment by jorges4lu2** [comment]
Thanks for your answer. 

I think I wrote/expressed wrong. What I mean is I want to assign 1 channel from epg to multiple channels of my m3u list (It could be done with multiple <display-name>).

As you said the channel id is a unique key inside the XML EPG.

This is a piece of my epg source:
```xml
<channel id="Discovery.Kids.HDTV.(Latin.America).(DKIDSHD).ar">
    <url>http://www.tvguide.com</url>
    <display-name lang="en">Discovery.Kids.HDTV.(Latin.America).(DKIDSHD).ar</display-name>
    <icon src="http://schedulesdirect-api20141201-logos.s3.amazonaws.com/stationLogos/s16680_dark_360w_270h.png" />
  </channel>
```

This is what I'd like to get:
```xml
<channel id="Discovery.Kids.HDTV.(Latin.America).(DKIDSHD).ar">
    <url>http://www.tvguide.com</url>
    <display-name lang="en">Latino: Discovery Kids FHD</display-name>
    <display-name lang="en">Latino: Discovery Kids HD</display-name>
    <display-name lang="en">Latino: Discovery Kids HQ</display-name>
    <icon src="http://schedulesdirect-api20141201-logos.s3.amazonaws.com/stationLogos/s16680_dark_360w_270h.png" />
  </channel>
```
And this is what I've tried in the .config:

```json
"Discovery.Kids.HDTV.(Latin.America).(DKIDSHD).ar": {"hidden": false, "replace": [{"xpath": "./display-name", "attrib": "", "regex": "", "with": "Latino: Discovery Kids FHD"}]},
"Discovery.Kids.HDTV.(Latin.America).(DKIDSHD).ar": {"hidden": false, "replace": [{"xpath": "./display-name", "attrib": "", "regex": "", "with": "Latino: Discovery Kids HD"}]},
"Discovery.Kids.HDTV.(Latin.America).(DKIDSHD).ar": {"hidden": false, "replace": [{"xpath": "./display-name", "attrib": "", "regex": "", "with": "Latino: Discovery Kids HQ"}]}
```

But I only get the last replace of the config:
```xml
<channel id="Discovery.Kids.HDTV.(Latin.America).(DKIDSHD).ar">
    <url>http://www.tvguide.com</url>
    <display-name lang="en">Latino: Discovery Kids HQ</display-name>
    <icon src="http://schedulesdirect-api20141201-logos.s3.amazonaws.com/stationLogos/s16680_dark_360w_270h.png" />
  </channel>
```
Hoping I could express myself correctly this time and you could help me.

Thanks in any case!!!!!

**Comment by elbowz** [comment]
Hi @jorges4lu2, I perfectly understand your issue now.
Unfortunately *tv_grab_xml* can *"Parse, filter and change (by regex) an EPG xml file"*, but you want enlarge the xml replicating the same EPG for different channels.

At the end I think it's a very good and useful idea, but right now it's not easy implement this behavior with the current logic behind and my free time.

I leave the issue/request open, but I cannot provide an implementation time prevision about that

**Comment by jorges4lu2** [comment]
@elbowz thank you so much for dedicating some time to answer me. 

I perfectly understand you.

**Comment by elbowz** [comment]
HI @jorges4lu2 and sorry for the delay, but I had advised you :)

The new release add the possibility to append new xml element/tag. 

So, for example, you can add to your channel the tag:

```xml
<display-name lang="en">Latino: Discovery Kids HQ</display-name>
```

Adding your json config:

```json
"add": [
        {
          "xpath": ".",
          "xml": "<display-name lang=\"en\">Latino: Discovery Kids HQ</display-name>"
        }
```

See [it.config.json](https://github.com/elbowz/tv_grab_xml/blob/master/it.config.json) for more example.

I hope it works like expected...

**Comment by jorges4lu2** [comment]
Hi @elbowz,

This is simply AWESOME!!!!!!! 
What a great surprise I got this morning on my email. You made my day bro.

I just tested the new version and is working perfectly.  This I exactly what I needed.

Thank you so much for all your work. Greatly appreciated.

**Comment by elbowz** [comment]
ahahah...glad to know you still need it...and It works :)
